# Generated by Django 5.2.6 on 2025-10-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.IntegerField(primary_key=True, serialize=False)),
                ('buyer_address', models.CharField(max_length=42)),
                ('seller_address', models.CharField(max_length=42)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('contract_address', models.CharField(default='0x', max_length=42)),
                ('contract_abi', models.JSONField(default=dict)),
                ('temperature_threshold', models.FloatField(default=-8)),
                ('status', models.CharField(default='active', max_length=50)),
            ],
            options={
                'db_table': 'contracts',
                'managed': False,
            },
        ),
    ]
