# Generated by Django 5.2.6 on 2025-10-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=100)),
                ('alert_message', models.TextField()),
                ('severity', models.CharField(default='Warning', max_length=50)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alerts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IoTData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('battery_voltage', models.FloatField(blank=True, null=True)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_long', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('data_created_at', models.DateTimeField(unique=True)),
            ],
            options={
                'db_table': 'iot_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IoTDataHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('avg_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('duration_hours', models.IntegerField()),
                ('result', models.CharField(default='Normal', max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'iot_data_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=255)),
                ('adafruit_feed', models.CharField(max_length=255)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'iot_devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_eth', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
