# Generated by Django 5.2.6 on 2025-10-18 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_pendinguser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingUser',
        ),
    ]
