# Generated by Django 5.2.6 on 2025-10-01 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('user_role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('distributor', 'Distributor'), ('admin', 'Admin')], max_length=20)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('id_upload', models.FileField(blank=True, null=True, upload_to='ids/')),
                ('address_upload', models.FileField(blank=True, null=True, upload_to='addresses/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
