# Generated by Django 5.2.6 on 2025-10-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_m_address_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business_license',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
